# Generated by Django 5.0.6 on 2024-05-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0002_alter_persona_f_nacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='f_nacto',
            field=models.DateField(),
        ),
    ]
