# Generated by Django 5.0.6 on 2024-05-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0007_persona_pais_alter_persona_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('O', 'Otro'), ('F', 'Femenino'), ('M', 'Masculino')], default='O', max_length=1),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('tipo', models.CharField(choices=[('Anaconda', 'Anaconda'), ('Perro', 'Perro'), ('Gato', 'Gato'), ('Manatí', 'Manatí')], max_length=30)),
                ('edad', models.IntegerField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_orm.persona')),
            ],
        ),
    ]
