# Generated by Django 5.0.6 on 2024-05-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0009_alter_mascota_edad_alter_mascota_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='subtipo',
            field=models.CharField(choices=[('Perro', [('Kiltro', 'Kiltro'), ('Verde', 'Verde')]), ('Gato', [('Angora', 'Angora'), ('Volador', 'Volador')]), ('Sin subtipo', 'Sin Subtipo')], default='Sin subtipo', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Manatí', 'Manatí'), ('Gato', 'Gato'), ('Anaconda', 'Anaconda')], max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('O', 'Otro'), ('M', 'Masculino'), ('F', 'Femenino')], default='O', max_length=1),
        ),
    ]
