# Generated by Django 5.0.6 on 2024-05-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orm', '0010_mascota_subtipo_alter_mascota_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(null=True, upload_to='personas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('Manatí', 'Manatí'), ('Perro', 'Perro'), ('Gato', 'Gato'), ('Anaconda', 'Anaconda')], max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='O', max_length=1),
        ),
    ]
